### ISSUE TITLE
GIF dynamic banner image

### ISSUE THREAD

**Issue by auula** [yetone/mirdb#2]
你好，大佬看到你这个项目很不错，我想请问一下这个 ![](https://github.com/yetone/mirdb/raw/master/assets/logo.gif) ，这种上古 DOS 风格图片是使用什么工具生成的？我很喜欢这种风格的 GIF 图片，谢谢

**Comment by yetone** [comment]
我的这种原子朋克风格的 GIF 图片都是用 retro-term 这个 terminal 实现的：https://github.com/Swordfish90/cool-retro-term

**Comment by auula** [comment]
> 你好，大佬看到你这个项目很不错，我想请问一下这个

thank ❤️
